#markdown: rdiscount
#markdown: kramdown
#markdown: redcarpet
#redcarpet:
#    extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]
markdown: pandoc
pandoc:
  format: html5
  extensions: [smart, mathjax]

title:            Deep Learning - beta version
#lucktroy
subTitle:         Simple, Easy, Fast
plugins:          ./_plugins
description:
#A jekyll theme. Because I scribble.
url:              # Site url.
wishes:           O(∩_∩)O~
signoff:          lucktroy
# Your name.
disqus_shortname: lucktroygithubio
# disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:
# appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         HOME
    url:          /
  - name:         RESEARCH
    url:          /research
  - name:         PUBLICATIONS
    url:          /publications
  - name:         AWARDS
    url:          /awards
  - name:         ACTIVITIES
    url:          /activities
  - name:         LINKS
    url:          /links
  #- name:         CV
  #  url:          /zhang-cv.pdf
  #- name:         RESUME
  #  url:          /junbo-resume.pdf
pygments:         true
permalink:        pretty

