#markdown: rdiscount
#markdown: kramdown
#markdown: redcarpet
#redcarpet:
#    extensions: ["fenced_code_blocks", "tables", "highlight", "with_toc_data", "strikethrough", "underline"]
markdown: pandoc
pandoc:
  format: html5
  extensions: [smart, mathjax]

title:            Junbo Zhang | MSRA
#lucktroy
subTitle:         Simple, Easy, Fast
plugins_dir:  _plugins
description:
#A jekyll theme. Because I scribble.
url:              # Site url.
wishes:           O(∩_∩)O~
signoff:          lucktroy
# Your name.
disqus_shortname:
# disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:
# appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: 'UA-57015390-2' # set tracking, remove from /javascripts/basic.js if unwanted.

analytics :
  provider : google
  google:
    tracking_id : 'UA-57015390-2'
  getclicky :
    site_id

links:
  - name:         Home
    url:          /
  - name:         Research
    url:          /research
  - name:         Publications
    url:          /publications
  - name:         Awards
    url:          /awards
  - name:         Professional Activities
    url:          /activities
  - name:         Links
    url:          /links
  #- name:         CV
  #  url:          /zhang-cv.pdf
  #- name:         RESUME
  #  url:          /junbo-resume.pdf
highlighter:      pygments
permalink:        pretty

